name: colorgpt
description: "Color with GPT"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.2.0
  chat_gpt_sdk: ^2.2.5
  material_buttonx: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

